# Generated by Django 5.1.4 on 2025-01-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Usuario Normal'), (1, 'Gerente')], default=0, verbose_name='Tipo de Usuario'),
        ),
    ]
