# Generated by Django 5.1.4 on 2025-01-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagada'), ('rejected', 'Rechazada')], default='pending', max_length=10),
        ),
    ]
