# Generated by Django 5.1.4 on 2025-01-25 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_bill_reservation'),
        ('reservations', '0001_initial'),
        ('sports_spaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='sports_spaces.sportsspace'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='identification',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='reservations.reservation'),
        ),
    ]
