# Generated by Django 5.1.4 on 2025-01-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('opening_time', models.TimeField(verbose_name='Hora de Apertura')),
                ('closing_time', models.TimeField(verbose_name='Hora de Cierre')),
                ('has_parking', models.BooleanField(default=False)),
                ('has_showers', models.BooleanField(default=False)),
                ('has_lockers', models.BooleanField(default=False)),
                ('has_equipment', models.BooleanField(default=False)),
                ('images', models.ImageField(blank=True, null=True, upload_to='area/', verbose_name='Imágenes del Espacio')),
            ],
        ),
    ]
