# Generated by Django 5.1.4 on 2025-02-01 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('opening_time', models.TimeField(verbose_name='Hora de Apertura')),
                ('closing_time', models.TimeField(verbose_name='Hora de Cierre')),
                ('images', models.ImageField(blank=True, null=True, upload_to='area', verbose_name='Imágenes del Espacio')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('view_all_areas', 'Can view all areas')],
            },
        ),
        migrations.CreateModel(
            name='AreaService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_services', to='areas.area')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.additionalservice')),
            ],
            options={
                'unique_together': {('area', 'service')},
            },
        ),
    ]
