# Generated by Django 5.1.4 on 2025-01-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='area', verbose_name='Imágenes del Espacio'),
        ),
    ]
