# Generated by Django 5.1.4 on 2025-01-25 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_alter_area_options_alter_area_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='has_equipment',
        ),
        migrations.RemoveField(
            model_name='area',
            name='has_lockers',
        ),
        migrations.RemoveField(
            model_name='area',
            name='has_parking',
        ),
        migrations.RemoveField(
            model_name='area',
            name='has_showers',
        ),
    ]
