# Generated by Django 5.1.4 on 2025-01-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_sports',
            field=models.CharField(blank=True, max_length=255, verbose_name='Deportes favoritos'),
        ),
    ]
