# Generated by Django 5.1.4 on 2025-01-29 13:54

import account_settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_settings', '0002_userprofile_favorite_sports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(upload_to=account_settings.models.user_profile_picture_path, verbose_name='Foto de perfil'),
        ),
    ]
