# Generated by Django 5.1.4 on 2025-01-07 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_de_clientes', '0001_initial'),
        ('gestion_de_espacios_deportivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada')], max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_de_clientes.cliente')),
                ('espacio_deportivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_de_espacios_deportivos.espaciodeportivo')),
            ],
        ),
    ]
