# Generated by Django 5.1.4 on 2025-01-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Pendiente de confirmar', 'Pendiente de confirmar'), ('Reserva confirmada', 'Reserva confirmada'), ('Reserva cancelada', 'Reserva cancelada')], default='Pendiente de confirmar', max_length=30),
        ),
    ]
