# Generated by Django 5.1.4 on 2025-01-29 00:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservation_status'),
        ('sports_spaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Pagado'), _negated=True), fields=('space', 'date', 'start_time', 'end_time'), name='unique_reservation_active'),
        ),
    ]
