# Generated by Django 5.1.4 on 2025-01-29 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_unique_reservation_active'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservation',
            name='unique_reservation_active',
        ),
    ]
