# Generated by Django 5.1.4 on 2025-01-29 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_remove_reservation_unique_reservation_active'),
        ('sports_spaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('space', 'date', 'start_time', 'end_time')},
        ),
    ]
