# Generated by Django 5.1.4 on 2025-01-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='pago',
            name='correo',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
