# Generated by Django 5.1.4 on 2025-01-13 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0009_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
