# Generated by Django 5.1.4 on 2025-01-10 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportsSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Espacio Deportivo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('opening_time', models.TimeField(verbose_name='Hora de Apertura')),
                ('closing_time', models.TimeField(verbose_name='Hora de Cierre')),
                ('general_services', models.TextField(blank=True, verbose_name='Servicios Generales')),
                ('images', models.ImageField(blank=True, null=True, upload_to='sports_spaces/', verbose_name='Imágenes del Espacio')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Área')),
                ('sport_type', models.CharField(choices=[('Fútbol', 'Fútbol'), ('Basketball', 'Basketball'), ('Piscina', 'Piscina'), ('Gym', 'Gym'), ('Ecuavoley', 'Ecuavoley')], max_length=100, verbose_name='Tipo de Deporte')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='Capacidad')),
                ('sports_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='sports_spaces.sportsspace')),
            ],
        ),
    ]
