# Generated by Django 5.1.4 on 2025-01-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_spaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsspace',
            name='surface',
            field=models.CharField(choices=[('Sintética', 'Sintética'), ('Pasto Natural', 'Pasto Natural'), ('Cemento', 'Cemento'), ('Piscina', 'Piscina')], default='Sintética', max_length=16, verbose_name='Tipo de Superficie'),
        ),
    ]
