# Generated by Django 5.1.4 on 2025-01-19 01:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_spaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sportsspace',
            options={'ordering': ['-rating']},
        ),
        migrations.RemoveField(
            model_name='sportsspace',
            name='area',
        ),
        migrations.RemoveField(
            model_name='sportsspace',
            name='length',
        ),
        migrations.RemoveField(
            model_name='sportsspace',
            name='recommended_capacity',
        ),
        migrations.RemoveField(
            model_name='sportsspace',
            name='surface',
        ),
        migrations.RemoveField(
            model_name='sportsspace',
            name='width',
        ),
        migrations.AddField(
            model_name='sportsspace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='spaces/'),
        ),
        migrations.AddField(
            model_name='sportsspace',
            name='location',
            field=models.CharField(default='Loja', max_length=100),
        ),
        migrations.AddField(
            model_name='sportsspace',
            name='rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='sportsspace',
            name='cost_per_hour',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sportsspace',
            name='sport_type',
            field=models.CharField(choices=[('Fútbol', 'Fútbol'), ('Ecuavoley', 'Ecuavoley'), ('Piscina', 'Piscina')], default='Fútbol', max_length=100),
        ),
    ]
