# Generated by Django 5.1.4 on 2025-01-21 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0004_alter_area_options'),
        ('sports_spaces', '0002_alter_sportsspace_options_remove_sportsspace_area_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sportsspace',
            options={},
        ),
        migrations.RemoveField(
            model_name='sportsspace',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sportsspace',
            name='location',
        ),
        migrations.RemoveField(
            model_name='sportsspace',
            name='rating',
        ),
        migrations.AddField(
            model_name='sportsspace',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='css', to='areas.area'),
        ),
        migrations.AddField(
            model_name='sportsspace',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sportsspace',
            name='recommended_capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capacidad'),
        ),
        migrations.AddField(
            model_name='sportsspace',
            name='surface',
            field=models.CharField(choices=[('Sintética', 'Sintética'), ('Pasto Natural', 'Pasto Natural')], default='Sintética', max_length=16, verbose_name='Tipo de Superficie'),
        ),
        migrations.AddField(
            model_name='sportsspace',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sportsspace',
            name='cost_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sportsspace',
            name='sport_type',
            field=models.CharField(choices=[('Fútbol', 'Fútbol'), ('Basketball', 'Basketball'), ('Piscina', 'Piscina'), ('Gym', 'Gym'), ('Ecuavoley', 'Ecuavoley')], default=('Fútbol', 'Fútbol'), max_length=100, verbose_name='Tipo de Deporte'),
        ),
    ]
